# Generated by Django 4.1.6 on 2024-05-19 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BasicUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("selling", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("shipping_address", models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("return_address", models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name="Shoe",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("A Bathing Ape", "A Bathing Ape"),
                            ("Nike", "Nike"),
                            ("Adidas", "Adidas"),
                            ("Jordan", "Jordan"),
                            ("New Balance", "New Balance"),
                            ("Converse", "Converse"),
                            ("Balmain", "Balmain"),
                            ("Cactus Flea Plant Market", "Cactus Flea Plant Market"),
                            ("Maison Mihara", "Maison Mihara"),
                            ("Rick Owens", "Rick Owens"),
                            ("Comme des Garcons", "Comme des Garcons"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "other_brand",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A Bathing Ape", "A Bathing Ape"),
                            ("Nike", "Nike"),
                            ("Adidas", "Adidas"),
                            ("Jordan", "Jordan"),
                            ("New Balance", "New Balance"),
                            ("Converse", "Converse"),
                            ("Balmain", "Balmain"),
                            ("Cactus Flea Plant Market", "Cactus Flea Plant Market"),
                            ("Maison Mihara", "Maison Mihara"),
                            ("Rick Owens", "Rick Owens"),
                            ("Comme des Garcons", "Comme des Garcons"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("size", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("year_made", models.DateTimeField(verbose_name="month-year made")),
                ("used", models.BooleanField(default=False)),
                ("front_picture", models.ImageField(upload_to="creator-pictures/")),
                ("leftside_picture", models.ImageField(upload_to="creator-pictures/")),
                ("rightside_picture", models.ImageField(upload_to="creator-pictures/")),
                ("back_picture", models.ImageField(upload_to="creator-pictures/")),
                ("top_picture", models.ImageField(upload_to="creator-pictures/")),
                ("sole_picture", models.ImageField(upload_to="creator-pictures/")),
                (
                    "flaw_picture_1",
                    models.ImageField(
                        blank=True, null=True, upload_to="creator-pictures/"
                    ),
                ),
                (
                    "flaw_picture_2",
                    models.ImageField(
                        blank=True, null=True, upload_to="creator-pictures/"
                    ),
                ),
                (
                    "flaw_picture_3",
                    models.ImageField(
                        blank=True, null=True, upload_to="creator-pictures/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tender",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("size", models.CharField(max_length=200)),
                ("price", models.PositiveIntegerField()),
                (
                    "shoe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.shoe"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quality_Control",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            (
                                "Slightly Used W/ Original Box New",
                                "Slightly Used W/ Original Box New",
                            ),
                            (
                                "Heavily Used W/ Original Box New",
                                "Heavily Used W/ Original Box New",
                            ),
                            (
                                "Slightly Used W/ Original Box Damaged",
                                "Slightly Used W/ Original Box Damaged",
                            ),
                            (
                                "Heavily Used W/ Original Box Damaged",
                                "Heavily Used W/ Original Box Damaged",
                            ),
                            ("Slightly Used No Box", "Slightly Used No Box"),
                            ("Heavily Used No Box", "Heavily Used No Box"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "shoe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.shoe"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("size", models.CharField(max_length=200)),
                ("price", models.PositiveIntegerField()),
                (
                    "shoe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.shoe"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(max_length=16)),
                ("cvc", models.PositiveIntegerField()),
                ("expiry_date", models.DateField()),
                ("full_name", models.CharField(max_length=40)),
                ("zip_code", models.PositiveIntegerField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.basicuser"
                    ),
                ),
            ],
        ),
    ]
