# Generated by Django 4.1.6 on 2024-05-26 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_basicuser_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shoe",
            name="other_brand",
        ),
        migrations.AddField(
            model_name="offer",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="offer",
            name="expiration_duration",
            field=models.IntegerField(
                choices=[
                    (1, "1 day"),
                    (5, "5 days"),
                    (7, "7 days"),
                    (10, "10 days"),
                    (15, "15 days"),
                    (30, "30 days"),
                ],
                default=30,
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.buyer",
            ),
        ),
        migrations.AddField(
            model_name="shoe",
            name="colorway",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name="shoe",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.seller",
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.seller",
            ),
        ),
        migrations.AlterField(
            model_name="shoe",
            name="back_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="creator-pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="shoe",
            name="front_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="creator-pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="shoe",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="shoe",
            name="leftside_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="creator-pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="shoe",
            name="rightside_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="creator-pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="shoe",
            name="sole_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="creator-pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="shoe",
            name="top_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="creator-pictures/"
            ),
        ),
    ]
