# Generated by Django 4.1.6 on 2024-05-26 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_shoe_other_brand_offer_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="offer",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.buyer"
            ),
        ),
    ]
