# Generated by Django 4.1.6 on 2024-05-27 00:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_offer_shoe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoe",
            name="brand",
            field=models.CharField(
                choices=[
                    ("A Bathing Ape", "A Bathing Ape"),
                    ("Nike", "Nike"),
                    ("Adidas", "Adidas"),
                    ("Jordan", "Jordan"),
                    ("New Balance", "New Balance"),
                    ("Converse", "Converse"),
                    ("Balmain", "Balmain"),
                    ("Cactus Flea Plant Market", "Cactus Flea Plant Market"),
                    ("Maison Mihara", "Maison Mihara"),
                    ("Rick Owens", "Rick Owens"),
                    ("Comme des Garcons", "Comme des Garcons"),
                    ("Birkenstock", "Birkenstock"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="shoe",
            name="year_made",
            field=models.IntegerField(
                help_text="Enter the year the shoe was made.",
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2024),
                ],
            ),
        ),
    ]
