# Generated by Django 4.1.6 on 2024-05-27 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_shoe_brand_alter_shoe_year_made"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tender",
            name="price",
        ),
    ]
