# Generated by Django 4.1.6 on 2024-05-31 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_tender_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoe",
            name="year_made",
            field=models.IntegerField(
                blank=True,
                help_text="Enter the year the shoe was made.",
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2024),
                ],
            ),
        ),
    ]
