# Generated by Django 4.1.6 on 2024-05-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_shoe_year_made"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
