# Generated by Django 4.1.6 on 2024-05-31 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_offer_accepted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shoe",
            name="back_picture",
        ),
        migrations.RemoveField(
            model_name="shoe",
            name="flaw_picture_1",
        ),
        migrations.RemoveField(
            model_name="shoe",
            name="flaw_picture_2",
        ),
        migrations.RemoveField(
            model_name="shoe",
            name="flaw_picture_3",
        ),
        migrations.RemoveField(
            model_name="shoe",
            name="front_picture",
        ),
        migrations.RemoveField(
            model_name="shoe",
            name="leftside_picture",
        ),
        migrations.RemoveField(
            model_name="shoe",
            name="rightside_picture",
        ),
        migrations.RemoveField(
            model_name="shoe",
            name="sole_picture",
        ),
        migrations.RemoveField(
            model_name="shoe",
            name="top_picture",
        ),
        migrations.AddField(
            model_name="offer",
            name="accepted_tender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.tender",
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tender",
            name="accepted_offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.offer",
            ),
        ),
    ]
