# Generated by Django 4.1.6 on 2024-05-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_remove_shoe_back_picture_remove_shoe_flaw_picture_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoe",
            name="back_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="creator-pictures/"
            ),
        ),
        migrations.AddField(
            model_name="shoe",
            name="flaw_picture_1",
            field=models.ImageField(
                blank=True, null=True, upload_to="creator-pictures/"
            ),
        ),
        migrations.AddField(
            model_name="shoe",
            name="flaw_picture_2",
            field=models.ImageField(
                blank=True, null=True, upload_to="creator-pictures/"
            ),
        ),
        migrations.AddField(
            model_name="shoe",
            name="flaw_picture_3",
            field=models.ImageField(
                blank=True, null=True, upload_to="creator-pictures/"
            ),
        ),
        migrations.AddField(
            model_name="shoe",
            name="front_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="creator-pictures/"
            ),
        ),
        migrations.AddField(
            model_name="shoe",
            name="leftside_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="creator-pictures/"
            ),
        ),
        migrations.AddField(
            model_name="shoe",
            name="rightside_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="creator-pictures/"
            ),
        ),
        migrations.AddField(
            model_name="shoe",
            name="sole_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="creator-pictures/"
            ),
        ),
        migrations.AddField(
            model_name="shoe",
            name="top_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="creator-pictures/"
            ),
        ),
    ]
