# Generated by Django 4.1.6 on 2024-06-01 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_shoe_back_picture_shoe_flaw_picture_1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shoe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.shoe"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.basicuser"
                    ),
                ),
            ],
        ),
    ]
